import Head from "next/head";
import Image from "next/image";
import { useRef, useState } from "react";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";

let items = [
  {
    href: "https://nextjs.org/docs",
    title: "Documentation",
    text: "Find in-depth information about Next.js features and API.",
  },
  {
    href: "https://nextjs.org/learn",
    title: "Learn",
    text: "Learn about Next.js in an interactive course with quizzes!",
  },
  {
    href: "https://github.com/vercel/next.js/tree/canary/examples",
    title: "Examples",
    text: "Discover and deploy boilerplate example Next.js projects.",
  },
  {
    href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
    title: "Deploy",
    text: "Instantly deploy your Next.js site to a public URL with Vercel.",
  },
];

export default function Home() {
  const dragItem = useRef();
  const dragOverItem = useRef();
  const [list, setList] = useState(items);

  //
  const dragStart = (e, position) => {
    dragItem.current = position;
    console.log(e.target.innerHTML);
  };

  const dragEnter = (e, position) => {
    dragOverItem.current = position;
    console.log(e.target.innerHTML);
  };
  const drop = (e) => {
    const copyListItems = [...list];
    const dragItemContent = copyListItems[dragItem.current];
    const dargOverItem = copyListItems[dragOverItem.current];

    copyListItems.splice(dragItem.current, 1, dargOverItem);
    copyListItems.splice(dragOverItem.current, 1, dragItemContent);
    dragItem.current = null;
    dragOverItem.current = null;
    setList(copyListItems);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Move the cards by <code className={styles.code}>Darg & Drop</code>
        </p>

        <div className={styles.grid}>
          {list.map((item, index) => (
            <Card
              captureDragStart={(e) => dragStart(e, index)}
              captureDragEnter={(e) => dragEnter(e, index)}
              captureDragEnd={(e) => drop(e)}
              draggable={true}
              href={item.href}
              text={item.text}
              title={` ${index + 1} ` + item.title}
              key={Math.random()}
            />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
